### ISSUE TITLE
Trailing comma in package.json

### ISSUE THREAD

**Issue by thobiasn** [trevordixon/excel.js#49]
Trying to install excel using npm install excel --save results in this error.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.1.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'excel',
1 verbose cli   '--save' ]
2 info using npm@5.1.0
3 info using node@v8.1.1
4 verbose npm-session a134555576a0e26c
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 verbose stack Error: Failed to parse json
7 verbose stack Trailing comma in object at 18:3
7 verbose stack   },
7 verbose stack   ^
7 verbose stack     at parseError (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:435:11)
7 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:103:26)
7 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:50:5
7 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
7 verbose stack     at tryToString (fs.js:512:3)
7 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:500:12)
8 verbose cwd /Users/thobyy/Sandbox/dashboard
9 verbose Darwin 16.6.0
10 verbose argv "/usr/local/Cellar/node/8.1.1/bin/node" "/usr/local/bin/npm" "install" "excel" "--save"
11 verbose node v8.1.1
12 verbose npm  v5.1.0
13 error file /Users/thobyy/Sandbox/dashboard/package.json
14 error code EJSONPARSE
15 error Failed to parse json
15 error Trailing comma in object at 18:3
15 error   },
15 error   ^
16 error File: /Users/thobyy/Sandbox/dashboard/package.json
17 error Failed to parse package.json data.
17 error package.json must be actual JSON, not just JavaScript.
17 error
17 error Tell the package author to fix their package.json file. JSON.parse
18 verbose exit [ 1, true ]
```

**Comment by thobiasn** [comment]
im an idiot..
